path: './' # default is './'
urls:
  resume: https://objectstorage.ap-hyderabad-1.oraclecloud.com/n/ax77zqdyeqeb/b/nextcloud/o/resume.pdf
  github: https://github.com/insaanimanav
  gitlab: https://gitlab.com/insaanimanav
  linkedin: https://linkedin.com/in/insaanimanav


